Bump supported Python, macOS, and Windows versions
Specifically:
* Python 3.8 -> 3.11
* macOS 12 -> macOS 13 (supported by GH Actions + Parallels Desktop 19)
* Windows 7 -> 11 (supported by GH Actions + Parallels Desktop 19)

Benefits:
* Can build distribution artifacts in CI
* Can test Windows distribution artifact on Parallels Desktop 19
* Python upgrade unlocks various features:
    - Can use OS certificate store (#142)
    - Get closer to running CI on the latest supported Python versions (#202)
    - Nicer typing syntax
        - Generics on builtin types (ex: `list[str]`) without
          `from __future__ import annotations`
    - Can use tempfile.TemporaryDirectory(..., ignore_cleanup_errors=True)
      to ignore errors when deleting directories on Windows when a test
      fails and tries to clean up. Makes test failure output easier to read.

Resolves #50

diff --git a/.github/workflows/push-github-action.yml b/.github/workflows/push-github-action.yml
--- a/.github/workflows/push-github-action.yml
+++ b/.github/workflows/push-github-action.yml
@@ -11,7 +11,18 @@ on:
   # Run CI on the tip of any open pull request
   pull_request: null
   # Allow CI to be run manually in GitHub Actions UI
-  workflow_dispatch: null
+  workflow_dispatch:
+    inputs:
+      build_dist_artifact:
+        description: 'Build distribution artifact'
+        required: false
+        default: false
+        type: boolean
+
+# Customize the run name if the workflow is run manually.
+# Otherwise use the default run name (as specified by '').
+run-name: >
+  ${{ github.event_name == 'workflow_dispatch' && 'Manual CI run' || '' }}
 
 # 1. Test Crystal binary on each supported OS
 # 2. Test Crystal with Address Sanitizer on macOS specially
@@ -23,12 +34,6 @@ jobs:
       matrix:
         # NOTE: Test lots of Python versions to look for segfaults
         python-version:
-          - "3.8.18"
-          - "3.9.19"
-          # NOTE: Disable runs on some Python versions so that total number
-          #       of macOS CI runners is low enough to not need to wait for
-          #       available runners for very long
-          #- "3.10.14"
           - "3.11.9"
       fail-fast: false
     # NOTE: macos-13 is the last macOS runner to run on Intel rather than arm64
@@ -107,18 +112,14 @@ jobs:
     strategy:
       matrix:
         os:
-          # NOTE: Earliest macOS supported by Crystal is macOS 10.14
-          #- macos-10.14  # no longer supported by GitHub Actions
-          #- macos-10.15  # no longer supported by GitHub Actions
-          #- macos-11  # no longer supported by GitHub Actions after 6/28/2024
+          # NOTE: Earliest macOS supported by Crystal is macOS 13 (from the README)
           #- macos-12   # no longer supported by GitHub Actions after 12/3/2024
           - macos-13  # last macOS runner to run on Intel rather than arm64
           #- macos-14  # ARM-based; forces earlier incompatible Python version
           #- macos-15  # ARM-based
         # Test the earliest supported Python version only
         python-version:
-          - "3.8.18"
-          #- "3.9.19"
+          - "3.11.9"
       fail-fast: false
     runs-on: ${{ matrix.os }}
     timeout-minutes: 23  # 150% of normal time: 15 min, as of 2024-02-16
@@ -161,9 +162,18 @@ jobs:
 
       - name: Build .app and disk image
         working-directory: "./setup"
-        # --app-only: Don't build disk image because it intermittently fails
-        #             with "hdiutil create failed - Resource busy" in CI
-        run: "CRYSTAL_SUPPORT_SCREENSHOTS=True poetry run ./make-mac.sh --app-only"
+        run: |
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.build_dist_artifact }}" == "true" ]]; then
+            # If building a distribution artifact then also build the disk image
+            MAKE_ARGS=""
+          else
+            # --app-only:
+            # 1. Don't build the disk image because it intermittently fails
+            #    with "hdiutil create failed - Resource busy" in CI.
+            # 2. Don't build the disk image because it takes a long time.
+            MAKE_ARGS="--app-only"
+          fi
+          CRYSTAL_SUPPORT_SCREENSHOTS=True poetry run ./make-mac.sh $MAKE_ARGS
       
       - name: Enable core dumps
         if: env.ENABLE_CORE_DUMPS == 'true'
@@ -220,27 +230,28 @@ jobs:
       
       # NOTE: Must remove the --app-only option from make-mac.sh above to
       #       reinstate build of *.dmg disk image
-      #- name: Upload distribution artifact
-      #  # Only export distribution artifact for earliest supported Python and OS
-      #  if: (matrix.python-version == '3.8') && (matrix.os == 'macos-10.14')
-      #  uses: actions/upload-artifact@v3
-      #  with:
-      #    name: dist-mac
-      #    path: setup/dist-mac/*.dmg
-      #    if-no-files-found: warn
+      - name: Upload distribution artifact
+        if: ${{ github.event_name == 'workflow_dispatch' && 
+                github.event.inputs.build_dist_artifact == 'true' && 
+                matrix.python-version == '3.11.9' && 
+                matrix.os == 'macos-13' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: dist-mac
+          path: setup/dist-mac/*.dmg
+          if-no-files-found: warn
 
   build-linux:
     strategy:
       matrix:
         os:
-          # NOTE: Earliest Linux supported by Crystal is Ubuntu 22.04
+          # NOTE: Earliest Linux supported by Crystal is Ubuntu 22.04 (from the README)
           # NOTE: When adding new Linux versions, you may need
           #       to compile new wxPython .wgn files
           - ubuntu-22.04
         # Test the earliest supported Python version only
         python-version:
-          - "3.8.18"
-          #- "3.9.19"
+          - "3.11.9"
       fail-fast: false
     runs-on: ${{ matrix.os }}
     timeout-minutes: 9  # 150% of normal time: 5 min 29 sec, as of 2024-02-24
@@ -295,6 +306,21 @@ jobs:
           poetry run pip3 install wagon
           wget --no-verbose https://github.com/davidfstr/Crystal-Web-Archiver/releases/download/v1.4.0b/wxPython-4.2.1-py39-none-linux_x86_64.wgn
           poetry run wagon install wxPython-4.2.1-py39-none-linux_x86_64.wgn
+      - name: Install dependency wxPython from wagon (Python 3.11)
+        if: startsWith(matrix.python-version, '3.11.')
+        run: |
+          poetry run pip3 install wagon
+          wget --no-verbose https://github.com/davidfstr/Crystal-Web-Archiver/releases/download/v1.4.0b/wxPython-4.2.1-py311-none-linux_x86_64.wgn
+          poetry run wagon install wxPython-4.2.1-py311-none-linux_x86_64.wgn
+
+      - name: Fail if wxPython wagon is not available for this Python version
+        if: ${{ !startsWith(matrix.python-version, '3.8.') &&
+                !startsWith(matrix.python-version, '3.9.') &&
+                !startsWith(matrix.python-version, '3.11.') }}
+        run: |
+          echo "ERROR: No precompiled wxPython wagon is available for Python ${{ matrix.python-version }} on Linux."
+          echo "You must build a .wgn for this Python version and update the workflow."
+          exit 1
 
       - name: Install remaining dependencies with Poetry
         # If build takes a very long time, the precompiled .wgn in the 
@@ -334,16 +360,10 @@ jobs:
     strategy:
       matrix:
         os:
-          # NOTE: Earliest Windows supported by Crystal is Windows 7
-          #- windows-2012-r2  # based on Windows 7  # no longer supported by GitHub Actions
-          #- windows-2016  # based on Windows 8.1  # no longer supported by GitHub Actions
-          - windows-2019  # based on Windows 10 version 1809 (Redstone 5)
-          #- windows-2022  # based on Windows 10 version 21H2 (Vibranium)
-          #- windows-2025  # based on Windows 11 version 24H2 (Germanium)
-        # Test the earliest supported Python version only
+          # NOTE: Earliest Windows supported by Crystal is Windows 11 (from the README)
+          - windows-2025  # based on Windows 11 version 24H2 (Germanium)
         python-version:
-          - "3.8.10"
-          #- "3.9.13"
+          - "3.11.9"
       fail-fast: false
     runs-on: ${{ matrix.os }}
     timeout-minutes: 35  # 150% of normal time: 23 min, as of 2024-02-22
@@ -380,6 +400,11 @@ jobs:
       - name: Run non-UI tests
         run: poetry run python -m pytest
 
+      - name: Install Inno Setup 6
+        run: |
+          Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.4.3.exe" -OutFile "$env:USERPROFILE\\is.exe"
+          Start-Process -Wait -FilePath "$env:USERPROFILE\\is.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-"
+
       - name: Display Inno Setup in Program Files
         run: |
           dir "C:\Program Files (x86)"
@@ -406,8 +431,10 @@ jobs:
           if-no-files-found: ignore
       
       - name: Upload distribution artifact
-        # Only export distribution artifact for earliest supported Python and OS
-        if: (matrix.python-version == '3.8') && (matrix.os == 'windows-7')
+        if: ${{ github.event_name == 'workflow_dispatch' &&
+                github.event.inputs.build_dist_artifact == 'true' &&
+                matrix.python-version == '3.11.9' &&
+                matrix.os == 'windows-2025' }}
         uses: actions/upload-artifact@v4
         with:
           name: dist-win
